{
  "hash": "5a634f674801a0770bbb54c734cff292",
  "result": {
    "markdown": "---\ntitle: \"Example analysis\"\nformat: html\nbibliography: references.bib\n---\n\n\n# Background\n\nI will be doing a short data analysis on the built in air quality dataset in R.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(airquality)\ndim(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 153   6\n```\n:::\n\n```{.r .cell-code}\nhead(airquality, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R Wind Temp Month Day\n1    41     190  7.4   67     5   1\n2    36     118  8.0   72     5   2\n3    12     149 12.6   74     5   3\n```\n:::\n:::\n\n\n## Question\n\nOur question is: does temperature affect the ozone level?\n\n## Target Audience\n\nThe intended audience for this example analysis is anyone who wants to get a taste of the exploratory data analysis.\n\n## Data Description\n\nThis dataset we are using contains air quality measurements in New York between May and September in 1973. It contains 6 variables and 153 observations. This is a dataset in R that we have easy access to if anyone also wants to play with it.\n\n### Data Dictionary\n\n| Option    | Description |\n|------|----------|\n| `Ozone`    | Mean ozone in parts per billion from 1300 to 1500 hours at Roosevelt Island|\n| `Solar.R`    | Solar radiation in Langleys in the frequency band 4000--7700 Angstroms from 0800 to 1200 hours at Central Park |\n| `Wind` | Average wind speed in miles per hour at 0700 and 1000 hours at LaGuardia Airport |\n| `Temp` | Maximum daily temperature in degrees Fahrenheit at La Guardia Airport. |\n| `Month` | The Month the data is collected\n| `Day` | The Day the data is collected|\n\n### Link to data and data dictionary\n\nThe link to data and data dictionary [@datasource]: <https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/airquality>\n\n# Exploratory Data Analysis\n\nLet's first play with the dataset and get a taste of how it looks like using `dyplr` and `ggplot2` package.\n\nTo simplify the analysis, I will exclude the missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair <- drop_na(airquality)\n```\n:::\n\n\nAfter removing the missing values, we have 111 observations and 6 variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(air)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 111   6\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nair %>% summarise(mean_ozone = mean(Ozone),\n                  median_ozone = median(Ozone),\n                  sd_ozone = sd(Ozone),\n                  max_ozone = max(Ozone),\n                  min_ozone = min(Ozone))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  mean_ozone median_ozone sd_ozone max_ozone min_ozone\n1    42.0991           31 33.27597       168         1\n```\n:::\n:::\n\n\nOur ozone level is a very skewed dataset. Let's take a look at the histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air, aes(x=Ozone)) + geom_histogram() + \n  ggtitle(\"Histogram of Ozone Level\") + \n  geom_vline(aes(xintercept=mean(Ozone)),\n            color=\"blue\", linetype=\"dashed\", size=1) + \n  geom_vline(aes(xintercept=median(Ozone)),\n            color=\"red\", linetype=\"dashed\", size=1)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![We plot ozone levels in histogram form to get a better sense of the distribution](example_files/figure-html/fig-ozone-histogram-1.png){#fig-ozone-histogram width=672}\n:::\n:::\n\n\nThe blue dashed line is the mean while the red dashed line is the median of ozone level. Our dataset is very skewed.\n\nMean ozone from May to September is 42, median at 31, maximum at 168, and minimum at 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair  %>%\n  select(Ozone, Month, Day)%>% \n  slice_max(Ozone, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Month Day\n1   168     8  25\n2   135     7   1\n3   122     8   7\n```\n:::\n:::\n\n\nThe highest Ozone occurs in August and July.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair  %>%\n  select(Ozone, Month, Day)%>% \n  slice_min(Ozone, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Month Day\n1     1     5  21\n2     4     5  23\n3     6     5  18\n```\n:::\n:::\n\n\nThe lowest Ozone level occurs in May\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair %>% filter(Ozone > 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R Wind Temp Month Day\n1   115     223  5.7   79     5  30\n2   135     269  4.1   84     7   1\n3   108     223  8.0   85     7  25\n4   122     255  4.0   89     8   7\n5   110     207  8.0   90     8   9\n6   168     238  3.4   81     8  25\n7   118     225  2.3   94     8  29\n```\n:::\n:::\n\n\nThere are 7 days with Ozone level higher than 100, 6 out of 7 occurs in July and August with temperature over 80 degrees.\n\nIt looks like time in the year might affect Ozone level. So let's check it out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair %>% \n  group_by(Month) %>%\n  summarise(mean_ozone = mean(Ozone),\n            mean_temp = mean(Temp),\n            sd_temp = sd(Temp),\n            median_temp = median(Temp),\n            max_temp = max(Temp),\n            min_temp = min(Temp),\n            count = n()) %>%\n  arrange(desc(mean_temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 8\n  Month mean_ozone mean_temp sd_temp median_temp max_temp min_temp count\n  <int>      <dbl>     <dbl>   <dbl>       <dbl>    <int>    <int> <int>\n1     7       59.1      83.9    4.44          84       92       73    26\n2     8       60        83.7    7.05          81       97       72    23\n3     6       29.4      78.2    7.84          77       90       65     9\n4     9       31.4      76.9    8.50          76       93       63    29\n5     5       24.1      66.5    6.63          66       81       57    24\n```\n:::\n:::\n\n\nJuly has the highest mean, median, and standard deviation of temperature, but August is only a little bit behind in mean tempature. August has slightly higher mean Ozone level compared to July. May has the lowest mean Ozone and mean temperature\n\nBelow is a photo of ozone level over the years. Based on this, we suspect that the ozone level is related to time and temperature. Let's do more analysis\n\n![](images/ozone-temp.png)\n\n[[Source | Air Pollution in NYC: Causes, Effects, and Solutions] [@imagesource](https://earth.org/air-pollution-in-nyc/)]\n\n::: callout-tip\nIn scatterplots, flexibly play with color, dot size, dot shapes to add more information to the plots\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air, aes(x=Temp, y=Ozone)) + \n  geom_point(aes(col=Month)) + geom_smooth()+ ggtitle(\"Ozone level against temperature\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![Plot of Ozone against temperature shows that there is some relationship between Ozone level and temprature. The colors correspond to month; we can see more black dots in the lower temperature and lower ozone level range, and shallower dots in the higher temperature and higher ozone level range. The blue line represents the rrend line, which is roughly linear. the gray area is 95% confidence interval](example_files/figure-html/fig-ozone-temp-1.png){#fig-ozone-temp width=672}\n:::\n:::\n\n\n::: {.column-margin}\n\n\nThere are some dots that look like outlier or influential points that may have a major effect on fit of linear model. Right now, we might think that a second degree polynomial is a better fit because the trend line curvea bit. But without the influential points, a linear model might be an easier and better choice.\n\nThe book Linear Models in Statistics [@model] is a good reference if we want to proceed with fitting a model for this dataset\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air, aes(x=Solar.R, y=Ozone)) + \n  geom_point(aes(col=Month)) + ggtitle(\"Ozone level against solar radiation\") + xlab(\"Solar Radiation\")\n```\n\n::: {.cell-output-display}\n![There is no clear relationship between Ozone and solar radiation](example_files/figure-html/fig-ozone-solar-1.png){#fig-ozone-solar width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air, aes(x=Wind, y=Ozone)) + \n  geom_point(aes(col=Month))  + ggtitle(\"Ozone level against average wind speed\")\n```\n\n::: {.cell-output-display}\n![Ozone level and wind speed has a negative relationship. The higher the wind speed, the lower the ozone level](example_files/figure-html/fig-ozone-wind-1.png){#fig-ozone-wind width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(air, aes(x=Day, y=Ozone)) + \n  geom_point()  + facet_grid(cols = vars(Month))  + ggtitle(\"Ozone level across days\")\n```\n\n::: {.cell-output-display}\n![We plot ozone levels across days separated by months. There is no strong relationship between the ozone levels and the specific days in the month.](example_files/figure-html/fig-ozone-days-1.png){#fig-ozone-days width=672}\n:::\n:::\n\n\n\n::: callout-note\nWe have used `select`, `slice_max`, `group_by`, `summarize`, `filter`, `arrange` in the `dplyr` package\n:::\n\n::: callout-note\nWe have used `geom_point`, `geom_vline`, `geom_histogram`, `geom_smooth()` in the `ggplot2` package, and `facet_grid()`\n:::\n\n## Modelling\n\nBased on the scatter plots, we think that there might be a linear relationship between ozone level and temperature. The simple linear regression confirms our thoughts. Temp is statistically significant with a p value < 2e-16\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.out <- lm(Ozone ~ Temp, data = air)\nsummary(lm.out)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Ozone ~ Temp, data = air)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-40.922 -17.459  -0.874  10.444 118.078 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -147.6461    18.7553  -7.872 2.76e-12 ***\nTemp           2.4391     0.2393  10.192  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 23.92 on 109 degrees of freedom\nMultiple R-squared:  0.488,\tAdjusted R-squared:  0.4833 \nF-statistic: 103.9 on 1 and 109 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nBut we also see that the temperature is related to month. When we adjusts for month, the temperature is still signicant, although the covariate month is not. The relationship between ozone level and month is through temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.out.2 <- lm(Ozone ~ Temp + Month, data = air)\nsummary(lm.out.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Ozone ~ Temp + Month, data = air)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-41.814 -14.587   0.031  11.468 120.272 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -138.7831    18.8220  -7.373 3.57e-11 ***\nTemp           2.6739     0.2568  10.412  < 2e-16 ***\nMonth         -3.7596     1.6610  -2.264   0.0256 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 23.48 on 108 degrees of freedom\nMultiple R-squared:  0.5112,\tAdjusted R-squared:  0.5021 \nF-statistic: 56.46 on 2 and 108 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\nIn our full model, temperature and wind are the two most statistically significant predictors, which coincides with our exploratory data analysis in the previous section\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm.out.3 <- lm(Ozone ~ Temp + Month + Wind + Solar.R, data = air)\nsummary(lm.out.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Ozone ~ Temp + Month + Wind + Solar.R, data = air)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-35.870 -13.968  -2.671   9.553  97.918 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -58.05384   22.97114  -2.527   0.0130 *  \nTemp          1.87087    0.27363   6.837 5.34e-10 ***\nMonth        -2.99163    1.51592  -1.973   0.0510 .  \nWind         -3.31651    0.64579  -5.136 1.29e-06 ***\nSolar.R       0.04960    0.02346   2.114   0.0368 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.9 on 106 degrees of freedom\nMultiple R-squared:  0.6199,\tAdjusted R-squared:  0.6055 \nF-statistic: 43.21 on 4 and 106 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n# Summary\n\nIn conclusion, temperature does affect ozone level significantly. The scatter plot of ozone level against temperature shows a rough linear relationship, while the linear model confirms that this predictor is a statistically significant. We at first suspected that month relates to ozone level, but adjusting for temperature makes month not significant predictor for ozone level. Days in the month and solar radiation do not show significant linear relationship with Ozone level.\n\n# Functions used\n\n| Package    | Functions |\n| -- | ----- |\n| `dplyr` | `select()`, `slice_max()`, `group_by()`, `summarize()`, `filter()`, `arrange()`|\n| `tidyr` | `drop_na()` |\n| `ggplot2` | `geom_point()`, `geom_vline()`, `geom_histogram()`, `geom_smooth()` |\n| | `facet_grid()` |\n\n",
    "supporting": [
      "example_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}